import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Contact from '../pages/Contact'
import About from '../pages/About'
import Link from 'next/link'
import Navbar from '../Components/Navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mini Portfolio Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div>
        
     <Navbar/>

</div>
      <main className={styles.main}>

<div style={{borderRadius: '60px',overflow: 'hidden'}}>
  <Image src="/profile.jpg" alt=" " width={200} height={200}/></div>

        <div className={styles.description}>

            <h2>Mthokozisi Nxumalo</h2>
            <h1>Software Developer Graduate.</h1>
        </div>

        <p> As a recent ICT graduate I am seeking challenging career with a progressive organization
        that provide the opportunity to capitalize my coding, analytical skills and abilities in IT field.
        I would like to be a part of SOVTEC Team because I like their SPEX and it one of the most progressive 
        company that I have been always willing to join. I believe that with Sovtech, within a short period I
         will be able to get the most skills that I need to become a best full stack developer. </p> 
       
      
     
        <div className={styles.grid}>
          <a className={styles.card}>
          <p><Link href="/About">About Me &rarr;</Link></p>
          </a>

          <a className={styles.card}>
          <p>  <Link href="/Contact"> My Contact &rarr;</Link></p>
          </a>
        </div>
      </main>
                                <About/>
                                <Contact/>
      <footer className={styles.footer}>
        <a
        >
          Copyright 2022 - Developed by MT. All rights reserved{' '}
          <span className={styles.logo}>
          </span>
        </a>
      </footer>
    </div>
  )
}
